name: CI

on: [push]

jobs:
  test:
    name: Test Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test File Listing
        uses: ./
        env:
          OS_AUTH_URL: ${{secrets.OS_AUTH_URL}}
          OS_PASSWORD: ${{secrets.OS_PASSWORD}}
          OS_USERNAME: ${{secrets.OS_USERNAME}}
          OS_TENANT_NAME: ${{secrets.OS_TENANT_NAME}}
          OS_USER_DOMAIN_NAME: ${{secrets.OS_USER_DOMAIN_NAME}}
